### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by byron-devika** [VincentCATILLON/react-native-confetti-cannon#17]
Hi,

Are there plans for types support for this in the future?

"Could not find a declaration file for module 'react-native-confetti-cannon'. '../node_modules/react-native-confetti-cannon/src/index.js' implicitly has an 'any' type.

Try `npm install @types/react-native-confetti-cannon` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-confetti-cannon';`ts(7016)"

**Comment by leofontes** [comment]
For now you can add a file anywhere in your project ending in `.d.ts` for example `confetti-cannon.d.ts` and inside the file:

```
declare module 'react-native-confetti-cannon' {
  export * from 'react-native-confetti-cannon'
}
```

Hopefully they add the support in a future version

**Comment by EricLewe** [comment]
Can confirm that a Nokia 6 TA-1021 with android version 9 manage to render it (debug mode). Will update again once I have used it on published apk.

**Comment by VincentCATILLON** [comment]
Hi @byron-devika , sorry for the long delay. 

Yes, TS is in the migration plan as it's more used than Flow. Flow definitions files will remain to be able to use it in projects using flow :)

**Comment by VincentCATILLON** [comment]
Done in #33

**Comment by byron-devika** [comment]
Thank you @VincentCATILLON & @junhoyeo 
Much appreciated!
