### ISSUE TITLE
Performance issue when I use over 100 confetti

### ISSUE THREAD

**Issue by Mkolakoglu** [VincentCATILLON/react-native-confetti-cannon#18]
Hi, I am facing performance issues when I increase the confetti count over 100. Is there a way to resolve this?

I am testing it on iPhone Xs.

Versions:
`"react": "16.9.0"`
`"react-native": "0.60.5",`

Thanks in advance!

**Comment by VincentCATILLON** [comment]
Hi @Mkolakoglu,

as particles are renderered in parallel, you can have some limitations due to device specs, and it's strongly advised to limit the number of items you're rendering (more than 100 is a lot).

Maybe, we can use GPU instead of CPU to improve performances and add a row in the README to define it.

Feel free to tell me if you have any other idea

**Comment by denisk20** [comment]
@VincentCATILLON Is it easy to switch to GPU rendering? Maybe we can create pull request for that setting?

**Comment by VincentCATILLON** [comment]
@Mkolakoglu @denisk20 

I'm proud to tell you that the 1.2.0 release is out, using the native driver to render animations, which increase the performances as you can see in this [PR](https://github.com/VincentCATILLON/react-native-confetti-cannon/pull/21)

Hope you can use a lot of confettis right now ;)

**Comment by denisk20** [comment]
@VincentCATILLON thank you very much for your work!

**Comment by VincentCATILLON** [comment]
you're welcome :)

**Comment by Mkolakoglu** [comment]
Hi @VincentCATILLON, thanks once again for the fix :) It's working much more smoother on RN 0.62.

However, I just wanted to give an heads up. I think, `useNativeDriver` for `rotateZ` is not supported for lower RN versions. The screenshot is for the version `0.60.5` :

![Simulator Screen Shot - iPhone 8 - 2020-04-30 at 11 39 40](https://user-images.githubusercontent.com/16003411/80700455-0f29ec80-8ade-11ea-8e49-08f3c25db817.png)

Converting `rotateZ` to `rotate` is fixing this issue.

**Comment by VincentCATILLON** [comment]
@Mkolakoglu you're right, i'll do a patch asap (1.2.1) to fix this

**Comment by VincentCATILLON** [comment]
@Mkolakoglu can you try the 1.2.2 release ? :)

**Comment by Mkolakoglu** [comment]
Working as butter :) Congrats!
