### ISSUE TITLE
Getting glitch issue with some of Samsung and Motorola Android device 

### ISSUE THREAD

**Issue by sujallinex** [VincentCATILLON/react-native-confetti-cannon#30]
We can see Confetti glitch in some of the Samsung and Motorola Android like Samsung Galaxy M30, Moto one power.
Some of particle size increase to huge size and We can see some lines remains on bottom in this devices.

![Screenshot 2020-06-26 at 12 09 28 PM](https://user-images.githubusercontent.com/64072481/85829034-48fa3500-b7a7-11ea-8fcc-ee5429adf315.png)
![Screenshot 2020-06-26 at 12 09 18 PM](https://user-images.githubusercontent.com/64072481/85829038-4bf52580-b7a7-11ea-8f60-b65f6b55d67b.png)

the confetti stays at the bottom and do not disappear at the end even if I have added fadeOut=true

Note that it is working fine with iOS and Some other device.

**Comment by ydv0121** [comment]
+1

**Comment by EricLewe** [comment]
Can confirm similar behavior on Samsung S10, can't see it in my emulator though
![image](https://user-images.githubusercontent.com/18601399/87037868-37744c80-c1ed-11ea-8708-2ed5ee56dacb.png)

**Comment by EricLewe** [comment]
@sujallinex tried to reduce the amount of particles?

Changing
`<ConfettiCannon fallSpeed={3000} count={40} origin={{x: -10, y: 0}} fadeOut={true}/>`
to
`<ConfettiCannon fallSpeed={1500} count={20} origin={{x: -10, y: 0}}/>`
seems to have made the error on the Samsung S10 go away, or maybe the bug was in another dependency which now have been updated? :thinking:

**Comment by VincentCATILLON** [comment]
Hi @sujallinex @EricLewe 

Can you please confirm that you got the error using `fadeOut` prop with the latest release ? and you don't have without it (false value by default) ?

I'll investigate so

**Comment by pipesorter** [comment]
@VincentCATILLON I made `fadeOut: false` it makes it even worse. Have the exact issue what @sujallinex said. I have this issue with my google pixel 3a, also in other pixel 2xl too. This library so good, wish this one thing is fixed.

**Comment by professorkolik** [comment]
@VincentCATILLON First of all thank you for your efforts to create so nice library, love it so much.
Observed this issue on

Pixel 4
"react-native": "0.63.2",
"react-native-confetti-cannon": "1.5.1",

Component config:
`<ConfettiCannon ref={confettiCannonRef} count={200} origin={{ x: 0, y: 0 }} />`

Tried with different count of confetti pieces, 50, 100, 150 same behaviour

**Comment by scrapecoder** [comment]
@professorkolik have you find any solution for this glitch issue?

**Comment by professorkolik** [comment]
@scrapecoder Unfortunately no, had to disable for Android now

**Comment by VincentCATILLON** [comment]
@scrapecoder @professorkolik @pipesorter @sujallinex @EricLewe i'll try to reproduce your issues on an emulator, can you share please your piece of code implementing the lib please ? It can help me to understand what's happening and how i can fix it so (if it's lib related)

**Comment by originalankur** [comment]
+1 We are observing this behavior on all new Samsung devices shipped in last 1 year.

**Comment by MinaFSedrak** [comment]
@VincentCATILLON  Any updates ???

**Comment by leezumstein** [comment]
I did some testing using [`patch-package`](https://github.com/ds300/patch-package) and I believe we're just missing a `{ perspective: 100 }` transform in the transform array (see documentation [here](https://reactnative.dev/docs/animations#bear-in-mind)).

Attached is the patch we're using in our own project to fix the animation issues we've seen on Android.  Would be open to submitting a PR, but haven't worked with Flow before.

[react-native-confetti-cannon+1.5.1.patch.txt](https://github.com/VincentCATILLON/react-native-confetti-cannon/files/6015167/react-native-confetti-cannon%2B1.5.1.patch.txt)

**Comment by VincentCATILLON** [comment]
Hi everyone, this bug has been fixed and released under the [1.5.2](https://github.com/VincentCATILLON/react-native-confetti-cannon/releases/tag/1.5.2) tag.
I'm closing the issue, feel free to add postiive or negative feedbacks after you tried the new release

**Comment by originalankur** [comment]
Thank you @VincentCATILLON
