### ISSUE TITLE
Storybook isn't really useful

### ISSUE THREAD

**Issue by jbcrestot** [VincentCATILLON/react-native-confetti-cannon#31]
As it's impossible to restart the animation on storybook, you can play with props but can't see the result. 😞 

To bad, it's seems a nice feature! 👍

**Comment by VincentCATILLON** [comment]
Hi @jbcrestot ,

Thanks for your interest.
For all users that are not confident with Storybook UI, in the web preview, you change the props, or triggers some actions like: `start`, `stop`, `resume` under the `Addons` tab

![Capture d’écran 2020-07-20 à 17 34 59](https://user-images.githubusercontent.com/8419208/87956603-8a80b600-caaf-11ea-8312-33ad9da113f0.png)
![Capture d’écran 2020-07-20 à 17 31 37](https://user-images.githubusercontent.com/8419208/87956276-23630180-caaf-11ea-873a-2b725c6800c9.png)

If you are need some documentations about it, follow that [link](https://storybook.js.org/addons/)

HPH 🤞
