### ISSUE TITLE
Screen flickering on Google Pixel 3A XL

### ISSUE THREAD

**Issue by iggirex** [VincentCATILLON/react-native-confetti-cannon#36]
During the animation different parts of the screen will flicker on/off.
When the animation stops, the flickering also stops.
This glitch never happened on the emulator on my computer, and I did try several different phone models on there. It only happens on a real device.
Another person on my team who has the regular Pixel 3 is reporting the same issue.

**Comment by OmarYuusf** [comment]
same here

**Comment by dereksyme** [comment]
Same here for my Xaomi Mi9

**Comment by WadhahEssam** [comment]
I got it on one plus 6t + galaxy s10

**Comment by NickLewry** [comment]
Same here unfortunately

**Comment by suhaga15** [comment]
I got it on one plus 7 as well

**Comment by MinaFSedrak** [comment]
Any updates ?

**Comment by leezumstein** [comment]
See my comment [here](https://github.com/VincentCATILLON/react-native-confetti-cannon/issues/30#issuecomment-782690392) on the related bug.  Believe this will solve the issue.

**Comment by VincentCATILLON** [comment]
Hi everyone, this bug has been fixed and released under the [1.5.2](https://github.com/VincentCATILLON/react-native-confetti-cannon/releases/tag/1.5.2) tag.
I'm closing the issue, feel free to add postiive or negative feedbacks after you tried the new release
