### ISSUE TITLE
Feature request: programmatic start/stop

### ISSUE THREAD

**Issue by npedrini** [VincentCATILLON/react-native-confetti-cannon#6]
Hi, is a programmatic start/stop on the roadmap for the near future? I could see that replacing the current auto-play functionality, or added in addition to it. Either way, that would make the library much more usable for my use case, and others I imagine. Thanks!

**Comment by VincentCATILLON** [comment]
Hi @npedrini, this is a great idea and i'll make it asap so :) 

Stay tuned 🙌

**Comment by VincentCATILLON** [comment]
Hi @npedrini @joeyscarim @zindigo @ElliotRoche

Just to tell you that the 1.4.0 release has been released with programmatic methods (start, stop, resume) to be able to fit with your needs. Don't forget to set `autoStart` to false in props :)

In addition, you can give callbacks to the component to listen animation state changes (`onAnimationStart`, `onAnimationStop`, `onAnimationResume` and `onAnimationEnd`)

**Comment by VincentCATILLON** [comment]
Now, you can define `autoStartDelay` to be able to run another animation and do some things like [that](https://github.com/VincentCATILLON/react-native-confetti-cannon/pull/28).

You can do it programmatically to, like [there](https://github.com/VincentCATILLON/react-native-confetti-cannon/blob/master/example/storybook/stories/index.js#L65)
