### ISSUE TITLE
not rendering on Android

### ISSUE THREAD

**Issue by ironchef1369** [VincentCATILLON/react-native-confetti-cannon#8]
Looks like there was a fix earlier for something like this, but its not working in Android 9, any idea?

**Comment by VincentCATILLON** [comment]
Hey @ironchef1369 , can you please share your code to spot the problem ?

**Comment by EricLewe** [comment]
I had no issue with the rendering on an android emulator using Android 9. I will update if I encounter any problems on android environment. Anyone investigated this issue further yet? 

@ironchef1369 what code are you using?

**Comment by EricLewe** [comment]
Can confirm that a Nokia 6 TA-1021 with android version 9 manage to render it (debug mode). Will update again once I have used it on published apk.

**Comment by VincentCATILLON** [comment]
@EricLewe did you tried with release ? :) it's already used in production in android 9, so it's probably due to your configuration or something you made with it (integration for example).

Can you share the steps (or integration) you made ?

**Comment by EricLewe** [comment]
@VincentCATILLON, tried with release now and there was no problems at all. So 99% certain to say, this issue was not related an error with the lib.

**Comment by VincentCATILLON** [comment]
@EricLewe thanks for your feedback, I’m confident with that as the code is only using RN api :)
