### ISSUE TITLE
onAnimationEnd - it's not exist - please add

### ISSUE THREAD

**Issue by mr-piratman** [VincentCATILLON/react-native-confetti-cannon#9]
actually, I want it just for making it in a loop..  so also possible to add a prop loop. 
but on animation end will be an amazing addition!
(I'm just don't want to take all of your code out of node-module >> for appreciation reasons. )

amazing module by the way. congrats

**Comment by VincentCATILLON** [comment]
Hi @mr-piratman, sorry for the long delay to answer, i'll add it soon :) 

Feel free to make pull requests if you're comfortable with

**Comment by VincentCATILLON** [comment]
Hi @mr-piratman can you try the last release (1.3.0) that includes animation callbacks (start and stop) ? :)
